---
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-ruff
      entry: nbqa ruff 
      name: nbqa-ruff
      args: [--fix]
      additional_dependencies: [ruff==0.0.286]
