name: islp
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyterlab
  - jupytext
  - matplotlib
  - numpy
  - pandas
  - pandas-stubs
  - python
  - scikit-learn
  - seaborn
  - statsmodels
