name: islp 
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter-lsp-python
  - jupyterlab
  - jupyterlab-lsp
  - jupyterlab-vim
  - numpy
  - pandas
  - pandas-stubs
  - python
  - ruff
  - scikit-learn
  - seaborn
  - statsmodels
