[tool.poetry]
name = "intro-statistical-learning"
version = "0.1.0"
description = "An Introduction to Statistical Learning - exercises"
authors = ["Pedro Mendes"]
license = "GPLv3"
readme = "README.md"
packages = [{include = "intro_statistical_learning"}]

[tool.poetry.dependencies]
matplotlib = "^3.7.2"
numpy = "^1.25.1"
pandas = "^2.0.3"
python = "^3.11"
seaborn = "^0.12.2"

[tool.poetry.group.dev.dependencies]
jupyterlab-vim = "^0.16.0"
python-lsp-server = {extras = ["all"], version = "^1.7.4"}
jupyterlab = ">=3.6.0,<4.0.0"
pylsp-mypy = "^0.6.7"
pyls-isort = "^0.2.2"
python-lsp-black = "^1.3.0"
jupyterlab-lsp = "^4.2.0"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
